/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated/agentes'
import { Route as AuthenticatedCongregacoesRouteImport } from './routes/_authenticated/congregacoes'
import { Route as AuthenticatedCredenciaisRouteImport } from './routes/_authenticated/credenciais'
import { Route as AuthenticatedMinhaSituacaoRouteImport } from './routes/_authenticated/minha-situacao'
import { Route as AuthenticatedObreirosRouteImport } from './routes/_authenticated/obreiros'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as ApiPublicAgentRelatorioMensalRouteImport } from './routes/api/public/agent/relatorio-mensal'
import { Route as ApiPublicAgentCongregacoesIndexRouteImport } from './routes/api/public/agent/congregacoes/index'
import { Route as ApiPublicAgentCongregacoesIdRouteImport } from './routes/api/public/agent/congregacoes/$id'
import { Route as ApiPublicAgentObreirosIndexRouteImport } from './routes/api/public/agent/obreiros/index'
import { Route as ApiPublicAgentObreirosIdRouteImport } from './routes/api/public/agent/obreiros/$id'
import { Route as ApiPublicAgentPagamentosIndexRouteImport } from './routes/api/public/agent/pagamentos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCongregacoesRoute =
  AuthenticatedCongregacoesRouteImport.update({
    id: '/congregacoes',
    path: '/congregacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCredenciaisRoute =
  AuthenticatedCredenciaisRouteImport.update({
    id: '/credenciais',
    path: '/credenciais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaSituacaoRoute =
  AuthenticatedMinhaSituacaoRouteImport.update({
    id: '/minha-situacao',
    path: '/minha-situacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObreirosRoute = AuthenticatedObreirosRouteImport.update({
  id: '/obreiros',
  path: '/obreiros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAgentRelatorioMensalRoute =
  ApiPublicAgentRelatorioMensalRouteImport.update({
    id: '/api/public/agent/relatorio-mensal',
    path: '/api/public/agent/relatorio-mensal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentCongregacoesIndexRoute =
  ApiPublicAgentCongregacoesIndexRouteImport.update({
    id: '/api/public/agent/congregacoes/',
    path: '/api/public/agent/congregacoes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentCongregacoesIdRoute =
  ApiPublicAgentCongregacoesIdRouteImport.update({
    id: '/api/public/agent/congregacoes/$id',
    path: '/api/public/agent/congregacoes/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentObreirosIndexRoute =
  ApiPublicAgentObreirosIndexRouteImport.update({
    id: '/api/public/agent/obreiros/',
    path: '/api/public/agent/obreiros/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentObreirosIdRoute =
  ApiPublicAgentObreirosIdRouteImport.update({
    id: '/api/public/agent/obreiros/$id',
    path: '/api/public/agent/obreiros/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentPagamentosIndexRoute =
  ApiPublicAgentPagamentosIndexRouteImport.update({
    id: '/api/public/agent/pagamentos/',
    path: '/api/public/agent/pagamentos/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/credenciais': typeof AuthenticatedCredenciaisRoute
  '/minha-situacao': typeof AuthenticatedMinhaSituacaoRoute
  '/obreiros': typeof AuthenticatedObreirosRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/api/public/agent/relatorio-mensal': typeof ApiPublicAgentRelatorioMensalRoute
  '/api/public/agent/congregacoes/$id': typeof ApiPublicAgentCongregacoesIdRoute
  '/api/public/agent/obreiros/$id': typeof ApiPublicAgentObreirosIdRoute
  '/api/public/agent/congregacoes/': typeof ApiPublicAgentCongregacoesIndexRoute
  '/api/public/agent/obreiros/': typeof ApiPublicAgentObreirosIndexRoute
  '/api/public/agent/pagamentos/': typeof ApiPublicAgentPagamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/credenciais': typeof AuthenticatedCredenciaisRoute
  '/minha-situacao': typeof AuthenticatedMinhaSituacaoRoute
  '/obreiros': typeof AuthenticatedObreirosRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/api/public/agent/relatorio-mensal': typeof ApiPublicAgentRelatorioMensalRoute
  '/api/public/agent/congregacoes/$id': typeof ApiPublicAgentCongregacoesIdRoute
  '/api/public/agent/obreiros/$id': typeof ApiPublicAgentObreirosIdRoute
  '/api/public/agent/congregacoes': typeof ApiPublicAgentCongregacoesIndexRoute
  '/api/public/agent/obreiros': typeof ApiPublicAgentObreirosIndexRoute
  '/api/public/agent/pagamentos': typeof ApiPublicAgentPagamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agentes': typeof AuthenticatedAgentesRoute
  '/_authenticated/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/_authenticated/credenciais': typeof AuthenticatedCredenciaisRoute
  '/_authenticated/minha-situacao': typeof AuthenticatedMinhaSituacaoRoute
  '/_authenticated/obreiros': typeof AuthenticatedObreirosRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/api/public/agent/relatorio-mensal': typeof ApiPublicAgentRelatorioMensalRoute
  '/api/public/agent/congregacoes/$id': typeof ApiPublicAgentCongregacoesIdRoute
  '/api/public/agent/obreiros/$id': typeof ApiPublicAgentObreirosIdRoute
  '/api/public/agent/congregacoes/': typeof ApiPublicAgentCongregacoesIndexRoute
  '/api/public/agent/obreiros/': typeof ApiPublicAgentObreirosIndexRoute
  '/api/public/agent/pagamentos/': typeof ApiPublicAgentPagamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agentes'
    | '/congregacoes'
    | '/credenciais'
    | '/minha-situacao'
    | '/obreiros'
    | '/pagamentos'
    | '/painel'
    | '/api/public/agent/relatorio-mensal'
    | '/api/public/agent/congregacoes/$id'
    | '/api/public/agent/obreiros/$id'
    | '/api/public/agent/congregacoes/'
    | '/api/public/agent/obreiros/'
    | '/api/public/agent/pagamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agentes'
    | '/congregacoes'
    | '/credenciais'
    | '/minha-situacao'
    | '/obreiros'
    | '/pagamentos'
    | '/painel'
    | '/api/public/agent/relatorio-mensal'
    | '/api/public/agent/congregacoes/$id'
    | '/api/public/agent/obreiros/$id'
    | '/api/public/agent/congregacoes'
    | '/api/public/agent/obreiros'
    | '/api/public/agent/pagamentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agentes'
    | '/_authenticated/congregacoes'
    | '/_authenticated/credenciais'
    | '/_authenticated/minha-situacao'
    | '/_authenticated/obreiros'
    | '/_authenticated/pagamentos'
    | '/_authenticated/painel'
    | '/api/public/agent/relatorio-mensal'
    | '/api/public/agent/congregacoes/$id'
    | '/api/public/agent/obreiros/$id'
    | '/api/public/agent/congregacoes/'
    | '/api/public/agent/obreiros/'
    | '/api/public/agent/pagamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAgentRelatorioMensalRoute: typeof ApiPublicAgentRelatorioMensalRoute
  ApiPublicAgentCongregacoesIdRoute: typeof ApiPublicAgentCongregacoesIdRoute
  ApiPublicAgentObreirosIdRoute: typeof ApiPublicAgentObreirosIdRoute
  ApiPublicAgentCongregacoesIndexRoute: typeof ApiPublicAgentCongregacoesIndexRoute
  ApiPublicAgentObreirosIndexRoute: typeof ApiPublicAgentObreirosIndexRoute
  ApiPublicAgentPagamentosIndexRoute: typeof ApiPublicAgentPagamentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/congregacoes': {
      id: '/_authenticated/congregacoes'
      path: '/congregacoes'
      fullPath: '/congregacoes'
      preLoaderRoute: typeof AuthenticatedCongregacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credenciais': {
      id: '/_authenticated/credenciais'
      path: '/credenciais'
      fullPath: '/credenciais'
      preLoaderRoute: typeof AuthenticatedCredenciaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-situacao': {
      id: '/_authenticated/minha-situacao'
      path: '/minha-situacao'
      fullPath: '/minha-situacao'
      preLoaderRoute: typeof AuthenticatedMinhaSituacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obreiros': {
      id: '/_authenticated/obreiros'
      path: '/obreiros'
      fullPath: '/obreiros'
      preLoaderRoute: typeof AuthenticatedObreirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent/relatorio-mensal': {
      id: '/api/public/agent/relatorio-mensal'
      path: '/api/public/agent/relatorio-mensal'
      fullPath: '/api/public/agent/relatorio-mensal'
      preLoaderRoute: typeof ApiPublicAgentRelatorioMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/congregacoes/': {
      id: '/api/public/agent/congregacoes/'
      path: '/api/public/agent/congregacoes'
      fullPath: '/api/public/agent/congregacoes/'
      preLoaderRoute: typeof ApiPublicAgentCongregacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/congregacoes/$id': {
      id: '/api/public/agent/congregacoes/$id'
      path: '/api/public/agent/congregacoes/$id'
      fullPath: '/api/public/agent/congregacoes/$id'
      preLoaderRoute: typeof ApiPublicAgentCongregacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/obreiros/': {
      id: '/api/public/agent/obreiros/'
      path: '/api/public/agent/obreiros'
      fullPath: '/api/public/agent/obreiros/'
      preLoaderRoute: typeof ApiPublicAgentObreirosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/obreiros/$id': {
      id: '/api/public/agent/obreiros/$id'
      path: '/api/public/agent/obreiros/$id'
      fullPath: '/api/public/agent/obreiros/$id'
      preLoaderRoute: typeof ApiPublicAgentObreirosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/pagamentos/': {
      id: '/api/public/agent/pagamentos/'
      path: '/api/public/agent/pagamentos'
      fullPath: '/api/public/agent/pagamentos/'
      preLoaderRoute: typeof ApiPublicAgentPagamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRoute
  AuthenticatedCongregacoesRoute: typeof AuthenticatedCongregacoesRoute
  AuthenticatedCredenciaisRoute: typeof AuthenticatedCredenciaisRoute
  AuthenticatedMinhaSituacaoRoute: typeof AuthenticatedMinhaSituacaoRoute
  AuthenticatedObreirosRoute: typeof AuthenticatedObreirosRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentesRoute: AuthenticatedAgentesRoute,
  AuthenticatedCongregacoesRoute: AuthenticatedCongregacoesRoute,
  AuthenticatedCredenciaisRoute: AuthenticatedCredenciaisRoute,
  AuthenticatedMinhaSituacaoRoute: AuthenticatedMinhaSituacaoRoute,
  AuthenticatedObreirosRoute: AuthenticatedObreirosRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAgentRelatorioMensalRoute: ApiPublicAgentRelatorioMensalRoute,
  ApiPublicAgentCongregacoesIdRoute: ApiPublicAgentCongregacoesIdRoute,
  ApiPublicAgentObreirosIdRoute: ApiPublicAgentObreirosIdRoute,
  ApiPublicAgentCongregacoesIndexRoute: ApiPublicAgentCongregacoesIndexRoute,
  ApiPublicAgentObreirosIndexRoute: ApiPublicAgentObreirosIndexRoute,
  ApiPublicAgentPagamentosIndexRoute: ApiPublicAgentPagamentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
