[build]
  command = "NITRO_PRESET=netlify npm run build"
  publish = ".output/public"

[functions]
  node_bundler = "esbuild"
  included_files = [".output/server/**/*", ".netlify/functions-internal/**/*"]

[[redirects]]
  from = "/assets/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
