[build]
  command = "bun run build"
  publish = ".output/public"

[functions]
  node_bundler = "esbuild"
  included_files = [".output/server/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
