[build]
  command = "NITRO_PRESET=netlify bun run build"
  publish = ".output/public"

[functions]
  node_bundler = "esbuild"
  included_files = [".output/server/**/*"]

[[redirects]]
  from = "/assets/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
